server:
  port: 8080
  servlet:
    context-path: /gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true

zuul:
  sensitive-headers: Cookie


# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

spring:
  application:
    name: gateway
  main:
    allow-circular-references: true
